### ISSUE TITLE
TOC/twin valkyers

### ISSUE THREAD

**Issue by scooterpro1** [tje3d/TrinityCore#12]
**Description:**
Esm nadaran + portalashunam rangesh jabejast
**Current behaviour:**
alan jofteshun nameshun unknowne bayad yeki dark bashe yeki light - portalam samte rast sefid bayad bashe samte chap meshki- jolo tar samte dari ke boss miad samte rast meshkiva samte sefid meshi -
**Expected behaviour:**
Namashun bayad fix bashe + range portala daghighan bar akse - yani rasti meshi chapi sefid - radif aghab tar rasti sefid - chapi meshki

**Steps to reproduce the problem:**
http://wowwiki.wikia.com/wiki/Twin_Val%27kyr

**Comment by tje3d** [comment]
Jahashoon dorost shod vali esmashoon doroste nemidoonam chera unknown neshoon mide
