### ISSUE TITLE
Arena + bg 

### ISSUE THREAD

**Issue by scooterpro1** [tje3d/TrinityCore#13]
**Description:**
chon server side aliance dare pvp khili ghrie fa alle

**Current behaviour:**
alan join nemishe aliance be aliance - agaram join she sari close mishe bg chon player kame

**Expected behaviour:**
yekari kon BG faghat warsong join she ke tedad paen hall mide + inke close nashe aslan 4v4 ham beshe aliance be aliancam ok bashe

**Steps to reproduce the problem:**

**Comment by tje3d** [comment]
felan enable shode. bug haro report kon
