### ISSUE TITLE
ICC/Fester

### ISSUE THREAD

**Issue by scooterpro1** [tje3d/TrinityCore#14]
**Description:**
spelle boss intrupe mishe

**Current behaviour:**
Boss ke cast mikone mitunan intrupe konan  - name spell :  [Pungent Blight] 

**Expected behaviour:**
nabayad intrupe beshe dg..

**Steps to reproduce the problem:**
http://wowwiki.wikia.com/wiki/Festergut

**Comment by tje3d** [comment]
Ghablan fix shode
