### ISSUE TITLE
Event bezar

### ISSUE THREAD

**Issue by scooterpro1** [tje3d/TrinityCore#16]
in goshada hosele level up nadaran - ye event bezar 7 ruz xp + skill worko hamechiro ziad kon chand ta player Biad

**Comment by tje3d** [comment]
Bejaye inke begi ziyad kon daghighan rate haro begoo

**Comment by scooterpro1** [comment]
Xp ro bokon 20 - Skill Work ro bokon 8 - 1 Shop Start game ham bezar item level 200 naix... 7 Ruz bashe base

**Comment by tje3d** [comment]
Liste itemhayi ke bayad too shop bashe ro bede pas

**Comment by scooterpro1** [comment]
kolle itemaye naix ro bezar dg
