### ISSUE TITLE
ICC/Fester

### ISSUE THREAD

**Issue by scooterpro1** [tje3d/TrinityCore#19]
**Description:**
Cast boss moshkel dare :  [Pungent Blight]

**Current behaviour:**
Alan in cast ro mishe intrupe kard

**Expected behaviour:**
Nabayad intrupe beshe
**Steps to reproduce the problem:**

http://wowwiki.wikia.com/wiki/Festergut

**Comment by tje3d** [comment]
Fix shode ghablan

**Comment by scooterpro1** [comment]
Fix nashode hanuz intrupe mishe
