### ISSUE TITLE
invalid target add

### ISSUE THREAD

**Issue by scooterpro1** [tje3d/TrinityCore#21]
**Description**:
ye addayi tu sholzar questam dare invalidan

**Current behaviour**: Tell us what happens
Alan addaro nemishe zad invalit targetan 
**Expected behaviour**: Tell us what should happen instead
bayaD BESHE zadeshun dg 2 3 ta queste marbot beheshun screen shotesho midam
![wowscrnshot_103117_120556](https://user-images.githubusercontent.com/33083047/32214482-3c33211e-bddc-11e7-906a-156d20d9b12b.jpg)
![wowscrnshot_103017_205613](https://user-images.githubusercontent.com/33083047/32214526-6084246e-bddc-11e7-8abf-94d6059d585e.jpg)
![wowscrnshot_103017_205756](https://user-images.githubusercontent.com/33083047/32214527-60baa89a-bddc-11e7-8af5-71cfff59abc8.jpg)
![wowscrnshot_103017_205806](https://user-images.githubusercontent.com/33083047/32214528-60ef68d2-bddc-11e7-9ffb-4ebb1da1f063.jpg)

**Steps to reproduce the problem**:
http://wowwiki.wikia.com/wiki/Quest:Forced_Hand
http://wowwiki.wikia.com/wiki/Quest:The_Mist_Isn%27t_Listening

**Comment by tje3d** [comment]
Fix shod
